language: objective-c
osx_image: xcode8

# Important to specify the simulator SDK, otherwise Travis CI will attempt to
# build for the real iPhone and fail due to code-signing issues.
# See https://docs.travis-ci.com/user/languages/objective-c for details.
xcode_sdk: iphonesimulator

xcode_project: AdvancedOperations.xcodeproj
xcode_scheme: AdvancedOperations
